### ISSUE TITLE
can you tell me how to use it

### ISSUE THREAD

**Issue by lkq13905940077** [HHHHhgqcdxhg/azurlane-fanpai#1]
can you tell me how to use it

**Comment by lkq13905940077** [comment]
怎么用

**Comment by QriDoki** [comment]
> 怎么用

README.md看不懂的话,  
直接上这个就可以玩了[https://blog.purecucumber.club/azurlane-fanpai/dist/index.html](https://blog.purecucumber.club/azurlane-fanpai/dist/index.html)
